Codeit-FE-5-part2-4/OpenMind

package-lock.json, package.json, src/App.js
=> [김한샘] Add: 라우터 추가

src/api/nameApi.js, src/pages/main/Main.jsx
=> [김한샘] Fix/mainpage

src/App.jsx, src/components/QuestionFeedList/QuestionFeedList.jsx, src/components/QuestionFeedList/QuestionFeedList.module.css, src/pages/PostPage/PostPage.jsx, src/utils/postpageAPI/getSubjectInfo.js, src/utils/postpageAPI/getSubjectQuestion.js
=> [김법균] postpage api를 통한 피드 불러오기

src/App.jsx, src/hooks/useUserProfileAndQuestions.js, src/pages/AnswerPage/AnswerPage.jsx, src/pages/PostPage/PostPage.jsx, src/utils/answerpageAPI/deleteFeed.js, src/utils/postQuestion.js
useParams 통해서 이제 저희 요구사항대로 경로접근 가능합니다
answerpage내에서 삭제버튼 누를시 list페이지로 리다이렉트 됩니다.
=> [김법균] 라우터 useParams 설정 및 answerpage 삭제 api 구현

src/components/QuestionFeedCard/AnswerContainer.jsx, src/components/QuestionFeedCard/QuestionFeedCard.jsx, src/components/QuestionFeedList/QuestionFeedList.jsx, src/components/QuestionModal/QuestionModal.jsx, src/components/TextAreaForm/TextAreaForm.jsx, src/hooks/useUserProfileAndQuestions.js, src/pages/AnswerPage/AnswerPage.jsx, src/pages/PostPage/PostPage.jsx, src/utils/answerpageAPI/createAnswer.js, src/utils/answerpageAPI/editAnswer.js
- 질문 작성시 모달창이 자동으로 닫히는 기능
- 질문 작성후 질문이 재랜더링 되는 기능
- 질문 답변하기 기능 및 재랜더링
- 질문 수정하기 기능 및 재랜더링
=> [PostPage, AnswerPage]

src/components/Pagination/Pagination.jsx, src/pages/QuestionCardListPage/QuestionCardListPage.jsx
지저분한 로직을 각 핸들러마다 특정 동작을 수행하면 해당 상태에 따라 api요청을 하도록 수정했습니다.
=> Repactor: 리스트페이지 로직 정리

src/components/QuestionFeedCard/QuestionFeedCard.module.css, src/components/TextAreaForm/TextAreaForm.jsx, src/components/TextAreaForm/TextAreaForm.module.css
=> feat: TextAreaForm 글자수 제한기능 추가

src/components/QuestionFeedCard/QuestionFeedCard.module.css
post, answer page 모바일 화면에서 박스 크기 조정
=> [배의진] post, answer page 모바일 화면에서 박스 크기 조정

src/components/ArrowButton/ArrowButton.jsx, src/pages/AnswerPage/AnswerPage.jsx, src/pages/PostPage/PostPage.jsx, src/pages/PostPage/PostPage.module.css
=> [배의진] 질문하기, 답변하기 페이지에 질문리스트로 이동하는 버튼 추가

src/components/ArrowButton/ArrowButton.jsx, src/components/Pagination/Pagination.jsx, src/components/Pagination/Pagination.module.css, src/components/QuestionCardList/QuestionCardList.jsx, src/components/QuestionCardList/QuestionCardList.module.css, src/pages/AnswerPage/AnswerPage.jsx, src/pages/QuestionCardListPage/QuestionCardListPage.jsx, src/pages/QuestionCardListPage/QuestionCardListPage.module.css
PC 사이즈
태블릿 사이즈
모바일사이즈
질문카드 없을 시 페이지 추가
=> [고학영] 스타일 리팩토링 및 질문리스트 컴포넌트 추가

src/components/FeedCardDropDown/FeedCardDropDown.jsx, src/components/PostReaction/PostReaction.jsx, src/components/PostReaction/PostReaction.module.css, src/components/QuestionFeedCard/QuestionFeedCard.jsx, src/components/QuestionFeedCard/QuestionFeedCard.module.css, src/pages/AnswerPage/AnswerPage.jsx
=> [배의진] 좋아요 싫어요 버튼 함수 컴포넌트로 분리

src/components/ListSortModal/ListSortModal.jsx, src/components/Pagination/Pagination.jsx
=> [고학영] chore 페이지네이션 애니메이션 추가

src/components/FeedCardDropDown/FeedCardDropDown.module.css, src/components/FloatingButton/FloatingButton.jsx, src/components/FloatingButton/FloatingButton.module.css, src/components/PostReaction/PostReaction.jsx, src/components/PostReaction/PostReaction.module.css, src/components/QuestionFeedCard/QuestionFeedCard.jsx, src/components/QuestionFeedCard/QuestionFeedCard.module.css, src/components/TextAreaForm/TextAreaForm.module.css, src/components/WarningModal/WarningModal.jsx, src/components/WarningModal/WarningModal.module.css, src/utils/postpageAPI/postReaction.js
버튼 애니메이션 추가
질문 텍스트 삐져나가는 문제 해결
경고 모달창 디자인 수정
애니메이션 추가
경고 모달창
질문 삐져나가는 거 해결
=> [배의진] 버튼 애니메이션 추가, 경고 모달창 디자인 수정 등

src/pages/MainPage/MainPage.jsx
AnimatePresence를 사용하여 애니메이션이 끝날시 부드럽게 사라지게끔 수정
=> [김한샘] 메인 페이지 > 애니메이션 추가 수정

src/components/PostReaction/PostReaction.jsx, src/components/PostReaction/PostReaction.module.css, src/components/QuestionFeedCard/QuestionFeedCard.jsx, src/components/QuestionFeedList/QuestionFeedList.jsx, src/pages/PostPage/PostPage.module.css, src/utils/postpageAPI/getSubjectQuestion.js
=> style: 질문 리스트 스크롤 애니메이션 추가 및 좋아요 버튼 애니메이션 수정

src/pages/NotFoundPage/NotFoundPage.module.css, src/pages/QuestionCardListPage/QuestionCardListPage.jsx, src/pages/QuestionCardListPage/QuestionCardListPage.module.css, src/utils/listPageApi/getSubjects.js
* 리스트 페이지에 데이터페칭 중 로딩로직을 추가하고 로딩상태가 true일때 로딩박스가 보이도록 하였습니다.
* 리스트 페이지에 데이터페칭 중 에러를 캐치하면 NotFoundPage컴포넌트를 렌더링하도록 하였습니다.
=> Feat loading error

src/components/PostReaction/PostReaction.jsx, src/components/QuestionFeedCard/QuestionFeedCard.jsx, src/utils/answerpageAPI/createAnswer.js, src/utils/answerpageAPI/toggleRejectAnswer.js
=> [배의진] 답변 거절하기 함수 간소화

src/components/ArrowButton/ArrowButton.jsx, src/components/ListHeader/ListHeader.jsx, src/components/Pagination/Pagination.jsx, src/components/PaginationNumberList/PaginationNumberList.jsx, src/components/PaginationNumberList/PaginationNumberList.module.css, src/pages/NotFoundPage/NotFoundPage.jsx
=> [고학영] refactor: 페이지네이션 페이지숫자 모듈분리

src/App.jsx, src/components/FeedCardDropDown/FeedCardDropDown.jsx, src/components/FloatingButton/FloatingButton.jsx, src/components/HoverAnimationDiv/HoverAnimationDiv.jsx, src/components/QuestionFeedCard/AnimatedDiv.jsx, src/components/QuestionFeedCard/AnswerContainer.jsx, src/components/QuestionFeedCard/AnswerStatusBar.jsx, src/components/QuestionFeedCard/QuestionFeedCard.jsx, src/components/QuestionFeedCard/QuestionFeedCard.module.css, src/components/QuestionFeedCard/QuestionInfoBar.jsx
- 수정상태에서 수정 취소가 가능합니다
- 거절된 답변은 수정하기와 답변삭제버튼이 표시되지않습니다
=> PostPage 최종 리팩터링 및 일부 기능 추가

src/components/ListSortModal/ListSortModal.jsx, src/components/ListSortModal/ListSortModal.module.css, src/components/QuestionCard/QuestionCard.module.css, src/components/QuestionCardList/QuestionCardList.jsx, src/components/QuestionCardList/QuestionCardList.module.css, src/pages/QuestionCardListPage/QuestionCardListPage.jsx, src/pages/QuestionCardListPage/QuestionCardListPage.module.css
* 페이지 이동 시에 방향에 따라 애니메이션 적용되도록 하였습니다.
* 솔트모달의 스타일을 링크버튼과 통일하여 페이지에 일관성을 주었습니다.
* 로딩시 로딩 텍스트를 지워서 자연스럽게 변경되도록 하였습니다.
=> List animation3

src/components/PaginationNumberList/PaginationNumberList.jsx, src/components/QuestionCard/QuestionCard.jsx, src/components/QuestionCard/QuestionCard.module.css, src/pages/QuestionCardListPage/QuestionCardListPage.jsx, src/pages/QuestionCardListPage/QuestionCardListPage.module.css
=> [고학영] refactor: 질문리스트페이지 리팩토링
